services:
  - type: web
    name: auth-service
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 24h
      - key: DATABASE_URL
        fromDatabase:
          name: auth-db
          property: connectionString

databases:
  - name: auth-db
    plan: free
    ipAllowList: []
